language: python
python:
  - 2.6
  - 2.7

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq graphviz

# Install packages
install:
  - pip install coverage coveralls pydot
  - pip install -e .

# Run test
script:
  - coverage run setup.py test

after_success:
  - coveralls