language: python
python:
  - 2.6
  - 2.7
  - "pypy"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq graphviz

# Install packages
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls

# Run test
script:
  - coverage run setup.py test

after_success:
  - coveralls