language: python
python:
  - 2.6
  - 2.7

# Install packages
install:
  - pip install coverage coveralls
  - pip install -e .

# Run test
script:
  - coverage run prov/tests/testModel.py

after_success:
  - coveralls