sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3

addons:
  apt:
    packages:
      - graphviz

cache:
  - pip
  - apt

# Install packages
install:
  - pip install --upgrade "setuptools<40.0.0"
  - pip install -r requirements.txt
  - pip install coverage coveralls

# Run test
script:
  - coverage run setup.py test

after_success:
  - coveralls
