language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

# Install packages
install:
  - pip install python-dateutil
  - python setup.py install
  - ls

# Run test
script:
  - python prov/tests/testModel.py
