language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - "pypy"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq graphviz

# Install packages
install:
  # Normal pydot does not install on Python 3, thus a special branch is currently (2015/01) needed.
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install https://bitbucket.org/prologic/pydot/get/ac76697320d6.zip ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install https://bitbucket.org/prologic/pydot/get/ac76697320d6.zip ; fi
  - pip install -r requirements.txt
  - pip install coverage coveralls

# Run test
script:
  - coverage run setup.py test

after_success:
  - coveralls
